using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
//using ZeroDep;


namespace MimeTypeExtension
{


    /// <summary>
    /// MIME-Type Extension for FileInfo and Url
    /// </summary>
    public static class MimeTypeExtension
    {
        private static MimeTypeList _mimeTypesList; 
        static MimeTypeExtension()
        {
            FillTypeList();
        }

        private static void FillTypeList()
        {
            if (_mimeTypesList != null)
                return;
            _mimeTypesList = new MimeTypeList
            {
                MimeTypes = new List<MimeType>
                {
                   new MimeType{Type = "..xml",Mime = "application/atom+xml"},
                    new MimeType{Type = ".123",Mime = "application/vnd.lotus-1-2-3"},
                    new MimeType{Type = ".323",Mime = "text/h323"},
                    new MimeType{Type = ".3dml",Mime = "text/vnd.in3d.3dml"},
                    new MimeType{Type = ".3g2",Mime = "video/3gpp2"},
                    new MimeType{Type = ".3gp",Mime = "video/3gpp"},
                    new MimeType{Type = ".3gp2",Mime = "video/3gpp2"},
                    new MimeType{Type = ".3gpp",Mime = "video/3gpp"},
                    new MimeType{Type = ".7z",Mime = "application/x-7z-compressed"},
                    new MimeType{Type = ".aab",Mime = "application/x-authorware-bin"},
                    new MimeType{Type = ".aac",Mime = "audio/aac"},
                    new MimeType{Type = ".aaf",Mime = "application/octet-stream"},
                    new MimeType{Type = ".aam",Mime = "application/x-authorware-map"},
                    new MimeType{Type = ".aas",Mime = "application/x-authorware-seg"},
                    new MimeType{Type = ".abw",Mime = "application/x-abiword"},
                    new MimeType{Type = ".ac",Mime = "application/pkix-attr-cert"},
                    new MimeType{Type = ".aca",Mime = "application/octet-stream"},
                    new MimeType{Type = ".acc",Mime = "application/vnd.americandynamics.acc"},
                    new MimeType{Type = ".accdb",Mime = "application/msaccess"},
                    new MimeType{Type = ".accde",Mime = "application/msaccess"},
                    new MimeType{Type = ".accdt",Mime = "application/msaccess"},
                    new MimeType{Type = ".ace",Mime = "application/x-ace-compressed"},
                    new MimeType{Type = ".acu",Mime = "application/vnd.acucobol"},
                    new MimeType{Type = ".acx",Mime = "application/internet-property-stream"},
                    new MimeType{Type = ".adp",Mime = "audio/adpcm"},
                    new MimeType{Type = ".adt",Mime = "audio/vnd.dlna.adts"},
                    new MimeType{Type = ".adts",Mime = "audio/vnd.dlna.adts"},
                    new MimeType{Type = ".aep",Mime = "application/vnd.audiograph"},
                    new MimeType{Type = ".afm",Mime = "application/octet-stream"},
                    new MimeType{Type = ".afp",Mime = "application/vnd.ibm.modcap"},
                    new MimeType{Type = ".ahead",Mime = "application/vnd.ahead.space"},
                    new MimeType{Type = ".ai",Mime = "application/postscript"},
                    new MimeType{Type = ".aif",Mime = "audio/x-aiff"},
                    new MimeType{Type = ".aifc",Mime = "audio/aiff"},
                    new MimeType{Type = ".aiff",Mime = "audio/aiff"},
                    new MimeType{Type = ".air",Mime = "application/vnd.adobe.air-application-installer-package+zip"},
                    new MimeType{Type = ".ait",Mime = "application/vnd.dvb.ait"},
                    new MimeType{Type = ".ami",Mime = "application/vnd.amiga.ami"},
                    new MimeType{Type = ".apk",Mime = "application/vnd.android.package-archive"},
                    new MimeType{Type = ".appcache",Mime = "text/cache-manifest"},
                    new MimeType{Type = ".application",Mime = "application/x-ms-application"},
                    new MimeType{Type = ".apr",Mime = "application/vnd.lotus-approach"},
                    new MimeType{Type = ".arc",Mime = "application/x-freearc"},
                    new MimeType{Type = ".art",Mime = "image/x-jg"},
                    new MimeType{Type = ".asd",Mime = "application/octet-stream"},
                    new MimeType{Type = ".asf",Mime = "video/x-ms-asf"},
                    new MimeType{Type = ".asi",Mime = "application/octet-stream"},
                    new MimeType{Type = ".asm",Mime = "text/plain"},
                    new MimeType{Type = ".aso",Mime = "application/vnd.accpac.simply.aso"},
                    new MimeType{Type = ".asr",Mime = "video/x-ms-asf"},
                    new MimeType{Type = ".asx",Mime = "video/x-ms-asf"},
                    new MimeType{Type = ".atc",Mime = "application/vnd.acucorp"},
                    new MimeType{Type = ".atom",Mime = "application/atom+xml"},
                    new MimeType{Type = ".atomcat",Mime = "application/atomcat+xml"},
                    new MimeType{Type = ".atomsvc",Mime = "application/atomsvc+xml:atom"},
                    new MimeType{Type = ".atx",Mime = "application/vnd.antix.game-component"},
                    new MimeType{Type = ".au",Mime = "audio/basic"},
                    new MimeType{Type = ".avi",Mime = "video/x-msvideo"},
                    new MimeType{Type = ".aw",Mime = "application/applixware"},
                    new MimeType{Type = ".axs",Mime = "application/olescript"},
                    new MimeType{Type = ".azf",Mime = "application/vnd.airzip.filesecure.azf"},
                    new MimeType{Type = ".azs",Mime = "application/vnd.airzip.filesecure.azs"},
                    new MimeType{Type = ".azw",Mime = "application/vnd.amazon.ebook"},
                    new MimeType{Type = ".bas",Mime = "text/plain"},
                    new MimeType{Type = ".bcpio",Mime = "application/x-bcpio"},
                    new MimeType{Type = ".bdf",Mime = "application/x-font-bdf"},
                    new MimeType{Type = ".bdm",Mime = "application/vnd.syncml.dm+wbxml"},
                    new MimeType{Type = ".bed",Mime = "application/vnd.realvnc.bed"},
                    new MimeType{Type = ".bh2",Mime = "application/vnd.fujitsu.oasysprs"},
                    new MimeType{Type = ".bin",Mime = "application/octet-stream"},
                    new MimeType{Type = ".bmi",Mime = "application/vnd.bmi"},
                    new MimeType{Type = ".bmp",Mime = "image/bmp"},
                    new MimeType{Type = ".box",Mime = "application/vnd.previewsystems.box"},
                    new MimeType{Type = ".btif",Mime = "image/prs.btif"},
                    new MimeType{Type = ".bz",Mime = "application/x-bzip"},
                    new MimeType{Type = ".bz2",Mime = "application/x-bzip2"},
                    new MimeType{Type = ".c",Mime = "text/x-c"},
                    new MimeType{Type = ".c11amc",Mime = "application/vnd.cluetrust.cartomobile-config"},
                    new MimeType{Type = ".c11amz",Mime = "application/vnd.cluetrust.cartomobile-config-pkg"},
                    new MimeType{Type = ".c4g",Mime = "application/vnd.clonk.c4group"},
                    new MimeType{Type = ".cab",Mime = "application/vnd.ms-cab-compressed"},
                    new MimeType{Type = ".calx",Mime = "application/vnd.ms-office.calx"},
                    new MimeType{Type = ".car",Mime = "application/vnd.curl.car"},
                    new MimeType{Type = ".cat",Mime = "application/vnd.ms-pki.seccat"},
                    new MimeType{Type = ".ccxml",Mime = "application/ccxml+xml,"},
                    new MimeType{Type = ".cda",Mime = "application/x-cdf"},
                    new MimeType{Type = ".cdbcmsg",Mime = "application/vnd.contact.cmsg"},
                    new MimeType{Type = ".cdf",Mime = "application/x-cdf"},
                    new MimeType{Type = ".cdkey",Mime = "application/vnd.mediastation.cdkey"},
                    new MimeType{Type = ".cdmia",Mime = "application/cdmi-capability"},
                    new MimeType{Type = ".cdmic",Mime = "application/cdmi-container"},
                    new MimeType{Type = ".cdmid",Mime = "application/cdmi-domain"},
                    new MimeType{Type = ".cdmio",Mime = "application/cdmi-object"},
                    new MimeType{Type = ".cdmiq",Mime = "application/cdmi-queue"},
                    new MimeType{Type = ".cdx",Mime = "chemical/x-cdx"},
                    new MimeType{Type = ".cdxml",Mime = "application/vnd.chemdraw+xml"},
                    new MimeType{Type = ".cdy",Mime = "application/vnd.cinderella"},
                    new MimeType{Type = ".cer",Mime = "application/pkix-cert"},
                    new MimeType{Type = ".cgm",Mime = "image/cgm"},
                    new MimeType{Type = ".chat",Mime = "application/x-chat"},
                    new MimeType{Type = ".chm",Mime = "application/mshelp"},
                    new MimeType{Type = ".chrt",Mime = "application/vnd.kde.kchart"},
                    new MimeType{Type = ".cif",Mime = "chemical/x-cif"},
                    new MimeType{Type = ".cii",Mime = "application/vnd.anser-web-certificate-issue-initiation"},
                    new MimeType{Type = ".cil",Mime = "application/vnd.ms-artgalry"},
                    new MimeType{Type = ".cla",Mime = "application/vnd.claymore"},
                    new MimeType{Type = ".class",Mime = "application/java-vm"},
                    new MimeType{Type = ".clkk",Mime = "application/vnd.crick.clicker.keyboard"},
                    new MimeType{Type = ".clkp",Mime = "application/vnd.crick.clicker.palette"},
                    new MimeType{Type = ".clkt",Mime = "application/vnd.crick.clicker.template"},
                    new MimeType{Type = ".clkw",Mime = "application/vnd.crick.clicker.wordbank"},
                    new MimeType{Type = ".clkx",Mime = "application/vnd.crick.clicker"},
                    new MimeType{Type = ".clp",Mime = "application/x-msclip"},
                    new MimeType{Type = ".cmc",Mime = "application/vnd.cosmocaller"},
                    new MimeType{Type = ".cmdf",Mime = "chemical/x-cmdf"},
                    new MimeType{Type = ".cml",Mime = "chemical/x-cml"},
                    new MimeType{Type = ".cmp",Mime = "application/vnd.yellowriver-custom-menu"},
                    new MimeType{Type = ".cmx",Mime = "image/x-cmx"},
                    new MimeType{Type = ".cnf",Mime = "text/plain"},
                    new MimeType{Type = ".cod",Mime = "image/cis-cod"},
                    new MimeType{Type = ".cpio",Mime = "application/x-cpio"},
                    new MimeType{Type = ".cpp",Mime = "text/plain"},
                    new MimeType{Type = ".cpt",Mime = "application/mac-compactpro"},
                    new MimeType{Type = ".crd",Mime = "application/x-mscardfile"},
                    new MimeType{Type = ".crl",Mime = "application/pkix-crl"},
                    new MimeType{Type = ".crt",Mime = "application/x-x509-ca-cert"},
                    new MimeType{Type = ".cryptonote",Mime = "application/vnd.rig.cryptonote"},
                    new MimeType{Type = ".csh",Mime = "application/x-csh"},
                    new MimeType{Type = ".csh",Mime = "application/x-csh"},
                    new MimeType{Type = ".csml",Mime = "chemical/x-csml"},
                    new MimeType{Type = ".csp",Mime = "application/vnd.commonspace"},
                    new MimeType{Type = ".css",Mime = "text/css"},
                    new MimeType{Type = ".csv",Mime = "text/csv"},
                    new MimeType{Type = ".cu",Mime = "application/cu-seeme"},
                    new MimeType{Type = ".cur",Mime = "application/octet-stream"},
                    new MimeType{Type = ".curl",Mime = "text/vnd.curl"},
                    new MimeType{Type = ".cww",Mime = "application/prs.cww"},
                    new MimeType{Type = ".dae",Mime = "model/vnd.collada+xml"},
                    new MimeType{Type = ".daf",Mime = "application/vnd.mobius.daf"},
                    new MimeType{Type = ".davmount",Mime = "application/davmount+xml"},
                    new MimeType{Type = ".dcr",Mime = "application/x-director"},
                    new MimeType{Type = ".dcurl",Mime = "text/vnd.curl.dcurl"},
                    new MimeType{Type = ".dd2",Mime = "application/vnd.oma.dd2+xml"},
                    new MimeType{Type = ".ddd",Mime = "application/vnd.fujixerox.ddd"},
                    new MimeType{Type = ".deb",Mime = "application/x-debian-package"},
                    new MimeType{Type = ".deploy",Mime = "application/octet-stream"},
                    new MimeType{Type = ".der",Mime = "application/x-x509-ca-cert"},
                    new MimeType{Type = ".dfac",Mime = "application/vnd.dreamfactory"},
                    new MimeType{Type = ".dib",Mime = "image/bmp"},
                    new MimeType{Type = ".dir",Mime = "application/x-director"},
                    new MimeType{Type = ".dis",Mime = "application/vnd.mobius.dis"},
                    new MimeType{Type = ".disco",Mime = "text/xml"},
                    new MimeType{Type = ".djvu",Mime = "image/vnd.djvu"},
                    new MimeType{Type = ".dll",Mime = "application/x-msdownload"},
                    new MimeType{Type = ".dll.config",Mime = "text/xml"},
                    new MimeType{Type = ".dlm",Mime = "text/dlm"},
                    new MimeType{Type = ".dmg",Mime = "application/x-apple-diskimage"},
                    new MimeType{Type = ".dna",Mime = "application/vnd.dna"},
                    new MimeType{Type = ".doc",Mime = "application/msword"},
                    new MimeType{Type = ".docm",Mime = "application/vnd.ms-word.document.macroEnabled.12"},
                    new MimeType{Type = ".docx",Mime = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"},
                    new MimeType{Type = ".dot",Mime = "application/msword"},
                    new MimeType{Type = ".dotm",Mime = "application/vnd.ms-word.template.macroEnabled.12"},
                    new MimeType{Type = ".dotx",Mime = "application/vnd.openxmlformats-officedocument.wordprocessingml.template"},
                    new MimeType{Type = ".dp",Mime = "application/vnd.osgi.dp"},
                    new MimeType{Type = ".dpg",Mime = "application/vnd.dpgraph"},
                    new MimeType{Type = ".dra",Mime = "audio/vnd.dra"},
                    new MimeType{Type = ".dsc",Mime = "text/prs.lines.tag"},
                    new MimeType{Type = ".dsp",Mime = "application/octet-stream"},
                    new MimeType{Type = ".dssc",Mime = "application/dssc+der"},
                    new MimeType{Type = ".dtb",Mime = "application/x-dtbook+xml"},
                    new MimeType{Type = ".dtd",Mime = "application/xml-dtd"},
                    new MimeType{Type = ".dts",Mime = "audio/vnd.dts"},
                    new MimeType{Type = ".dtshd",Mime = "audio/vnd.dts.hd"},
                    new MimeType{Type = ".dvi",Mime = "application/x-dvi"},
                    new MimeType{Type = ".dvr-ms",Mime = "video/x-ms-dvr"},
                    new MimeType{Type = ".dwf",Mime = "drawing/x-dwf"},
                    new MimeType{Type = ".dwg",Mime = "image/vnd.dwg"},
                    new MimeType{Type = ".dwp",Mime = "application/octet-stream"},
                    new MimeType{Type = ".dxf",Mime = "image/vnd.dxf"},
                    new MimeType{Type = ".dxp",Mime = "application/vnd.spotfire.dxp"},
                    new MimeType{Type = ".dxr",Mime = "application/x-director"},
                    new MimeType{Type = ".ecelp4800",Mime = "audio/vnd.nuera.ecelp4800"},
                    new MimeType{Type = ".ecelp7470",Mime = "audio/vnd.nuera.ecelp7470"},
                    new MimeType{Type = ".ecelp9600",Mime = "audio/vnd.nuera.ecelp9600"},
                    new MimeType{Type = ".edm",Mime = "application/vnd.novadigm.edm"},
                    new MimeType{Type = ".edx",Mime = "application/vnd.novadigm.edx"},
                    new MimeType{Type = ".efif",Mime = "application/vnd.picsel"},
                    new MimeType{Type = ".ei6",Mime = "application/vnd.pg.osasli"},
                    new MimeType{Type = ".eml",Mime = "message/rfc822"},
                    new MimeType{Type = ".emma",Mime = "application/emma+xml"},
                    new MimeType{Type = ".emz",Mime = "application/octet-stream"},
                    new MimeType{Type = ".eol",Mime = "audio/vnd.digital-winds"},
                    new MimeType{Type = ".eot",Mime = "application/vnd.ms-fontobject"},
                    new MimeType{Type = ".eps",Mime = "application/postscript"},
                    new MimeType{Type = ".epub",Mime = "application/epub+zip"},
                    new MimeType{Type = ".es",Mime = "application/ecmascript"},
                    new MimeType{Type = ".es3",Mime = "application/vnd.eszigno3+xml"},
                    new MimeType{Type = ".esd",Mime = "application/vnd.ms-cab-compressed"},
                    new MimeType{Type = ".esf",Mime = "application/vnd.epson.esf"},
                    new MimeType{Type = ".etx",Mime = "text/x-setext"},
                    new MimeType{Type = ".evy",Mime = "application/envoy"},
                    new MimeType{Type = ".exe",Mime = "application/x-msdownload"},
                    new MimeType{Type = ".exe.config",Mime = "text/xml"},
                    new MimeType{Type = ".exi",Mime = "application/exi"},
                    new MimeType{Type = ".ext",Mime = "application/vnd.novadigm.ext"},
                    new MimeType{Type = ".ez2",Mime = "application/vnd.ezpix-album"},
                    new MimeType{Type = ".ez3",Mime = "application/vnd.ezpix-package"},
                    new MimeType{Type = ".f",Mime = "text/x-fortran"},
                    new MimeType{Type = ".f4v",Mime = "video/x-f4v"},
                    new MimeType{Type = ".fbs",Mime = "image/vnd.fastbidsheet"},
                    new MimeType{Type = ".fcs",Mime = "application/vnd.isac.fcs"},
                    new MimeType{Type = ".fdf",Mime = "application/vnd.fdf"},
                    new MimeType{Type = ".fe_launch",Mime = "application/vnd.denovo.fcselayout-link"},
                    new MimeType{Type = ".fg5",Mime = "application/vnd.fujitsu.oasysgp"},
                    new MimeType{Type = ".fh",Mime = "image/x-freehand"},
                    new MimeType{Type = ".fif",Mime = "image/fif"},
                    new MimeType{Type = ".fig",Mime = "application/x-xfig"},
                    new MimeType{Type = ".fla",Mime = "application/octet-stream"},
                    new MimeType{Type = ".fli",Mime = "video/x-fli"},
                    new MimeType{Type = ".flo",Mime = "application/vnd.micrografx.flo"},
                    new MimeType{Type = ".flr",Mime = "x-world/x-vrml"},
                    new MimeType{Type = ".flv",Mime = "video/x-flv"},
                    new MimeType{Type = ".flw",Mime = "application/vnd.kde.kivio"},
                    new MimeType{Type = ".flx",Mime = "text/vnd.fmi.flexstor"},
                    new MimeType{Type = ".fly",Mime = "text/vnd.fly"},
                    new MimeType{Type = ".fm",Mime = "application/vnd.framemaker"},
                    new MimeType{Type = ".fnc",Mime = "application/vnd.frogans.fnc"},
                    new MimeType{Type = ".fpx",Mime = "image/vnd.fpx"},
                    new MimeType{Type = ".fsc",Mime = "application/vnd.fsc.weblaunch"},
                    new MimeType{Type = ".fst",Mime = "image/vnd.fst"},
                    new MimeType{Type = ".ftc",Mime = "application/vnd.fluxtime.clip"},
                    new MimeType{Type = ".fti",Mime = "application/vnd.anser-web-funds-transfer-initiation"},
                    new MimeType{Type = ".fvt",Mime = "video/vnd.fvt"},
                    new MimeType{Type = ".fxp",Mime = "application/vnd.adobe.fxp"},
                    new MimeType{Type = ".fzs",Mime = "application/vnd.fuzzysheet"},
                    new MimeType{Type = ".g2w",Mime = "application/vnd.geoplan"},
                    new MimeType{Type = ".g3",Mime = "image/g3fax"},
                    new MimeType{Type = ".g3w",Mime = "application/vnd.geospace"},
                    new MimeType{Type = ".gac",Mime = "application/vnd.groove-account"},
                    new MimeType{Type = ".gdl",Mime = "model/vnd.gdl"},
                    new MimeType{Type = ".geo",Mime = "application/vnd.dynageo"},
                    new MimeType{Type = ".gex",Mime = "application/vnd.geometry-explorer"},
                    new MimeType{Type = ".ggb",Mime = "application/vnd.geogebra.file"},
                    new MimeType{Type = ".ggt",Mime = "application/vnd.geogebra.tool"},
                    new MimeType{Type = ".ghf",Mime = "application/vnd.groove-help"},
                    new MimeType{Type = ".gif",Mime = "image/gif"},
                    new MimeType{Type = ".gim",Mime = "application/vnd.groove-identity-message"},
                    new MimeType{Type = ".glb",Mime = "model/gltf-binary"},
                    new MimeType{Type = ".gmx",Mime = "application/vnd.gmx"},
                    new MimeType{Type = ".gnumeric",Mime = "application/x-gnumeric"},
                    new MimeType{Type = ".gph",Mime = "application/vnd.flographit"},
                    new MimeType{Type = ".gqf",Mime = "application/vnd.grafeq"},
                    new MimeType{Type = ".gram",Mime = "application/srgs"},
                    new MimeType{Type = ".grv",Mime = "application/vnd.groove-injector"},
                    new MimeType{Type = ".grxml",Mime = "application/srgs+xml"},
                    new MimeType{Type = ".gsf",Mime = "application/x-font-ghostscript"},
                    new MimeType{Type = ".gtar",Mime = "application/x-gtar"},
                    new MimeType{Type = ".gtm",Mime = "application/vnd.groove-tool-message"},
                    new MimeType{Type = ".gtw",Mime = "model/vnd.gtw"},
                    new MimeType{Type = ".gv",Mime = "text/vnd.graphviz"},
                    new MimeType{Type = ".gxt",Mime = "application/vnd.geonext"},
                    new MimeType{Type = ".gz",Mime = "application/x-gzip"},
                    new MimeType{Type = ".h",Mime = "text/plain"},
                    new MimeType{Type = ".h261",Mime = "video/h261"},
                    new MimeType{Type = ".h263",Mime = "video/h263"},
                    new MimeType{Type = ".h264",Mime = "video/h264"},
                    new MimeType{Type = ".hal",Mime = "application/vnd.hal+xml"},
                    new MimeType{Type = ".hbci",Mime = "application/vnd.hbci"},
                    new MimeType{Type = ".hdf",Mime = "application/x-hdf"},
                    new MimeType{Type = ".hdml",Mime = "text/x-hdml"},
                    new MimeType{Type = ".hhc",Mime = "application/x-oleobject"},
                    new MimeType{Type = ".hhk",Mime = "application/octet-stream"},
                    new MimeType{Type = ".hhp",Mime = "application/octet-stream"},
                    new MimeType{Type = ".hlp",Mime = "application/mshelp"},
                    new MimeType{Type = ".hpgl",Mime = "application/vnd.hp-hpgl"},
                    new MimeType{Type = ".hpid",Mime = "application/vnd.hp-hpid"},
                    new MimeType{Type = ".hps",Mime = "application/vnd.hp-hps"},
                    new MimeType{Type = ".hqx",Mime = "application/mac-binhex40"},
                    new MimeType{Type = ".hta",Mime = "application/hta"},
                    new MimeType{Type = ".htc",Mime = "text/x-component"},
                    new MimeType{Type = ".htke",Mime = "application/vnd.kenameaapp"},
                    new MimeType{Type = ".htm",Mime = "text/html"},
                    new MimeType{Type = ".html",Mime = "text/html"},
                    new MimeType{Type = ".htmls",Mime = "text/html"},
                    new MimeType{Type = ".htt",Mime = "text/webviewhtml"},
                    new MimeType{Type = ".htt",Mime = "text/webviewhtml"},
                    new MimeType{Type = ".htx",Mime = "text/html"},
                    new MimeType{Type = ".hvd",Mime = "application/vnd.yamaha.hv-dic"},
                    new MimeType{Type = ".hvp",Mime = "application/vnd.yamaha.hv-voice"},
                    new MimeType{Type = ".hvs",Mime = "application/vnd.yamaha.hv-script"},
                    new MimeType{Type = ".hxt",Mime = "text/html"},
                    new MimeType{Type = ".i2g",Mime = "application/vnd.intergeo"},
                    new MimeType{Type = ".icc",Mime = "application/vnd.iccprofile"},
                    new MimeType{Type = ".ice",Mime = "x-conference/x-cooltalk"},
                    new MimeType{Type = ".ico",Mime = "image/x-icon"},
                    new MimeType{Type = ".ics",Mime = "text/calendar"},
                    new MimeType{Type = ".ief",Mime = "image/ief"},
                    new MimeType{Type = ".ifm",Mime = "application/vnd.shana.informed.formdata"},
                    new MimeType{Type = ".igl",Mime = "application/vnd.igloader"},
                    new MimeType{Type = ".igm",Mime = "application/vnd.insors.igm"},
                    new MimeType{Type = ".igs",Mime = "model/iges"},
                    new MimeType{Type = ".igx",Mime = "application/vnd.micrografx.igx"},
                    new MimeType{Type = ".iif",Mime = "application/vnd.shana.informed.interchange"},
                    new MimeType{Type = ".iii",Mime = "application/x-iphone"},
                    new MimeType{Type = ".imp",Mime = "application/vnd.accpac.simply.imp"},
                    new MimeType{Type = ".ims",Mime = "application/vnd.ms-ims"},
                    new MimeType{Type = ".inf",Mime = "application/octet-stream"},
                    new MimeType{Type = ".ins",Mime = "application/x-internet-signup"},
                    new MimeType{Type = ".ipfix",Mime = "application/ipfix"},
                    new MimeType{Type = ".ipk",Mime = "application/vnd.shana.informed.package"},
                    new MimeType{Type = ".irm",Mime = "application/vnd.ibm.rights-management"},
                    new MimeType{Type = ".irp",Mime = "application/vnd.irepository.package+xml"},
                    new MimeType{Type = ".isp",Mime = "application/x-internet-signup"},
                    new MimeType{Type = ".itp",Mime = "application/vnd.shana.informed.formtemplate"},
                    new MimeType{Type = ".IVF",Mime = "video/x-ivf"},
                    new MimeType{Type = ".ivp",Mime = "application/vnd.immervision-ivp"},
                    new MimeType{Type = ".ivu",Mime = "application/vnd.immervision-ivu"},
                    new MimeType{Type = ".jad",Mime = "text/vnd.sun.j2me.app-descriptor"},
                    new MimeType{Type = ".jam",Mime = "application/vnd.jam"},
                    new MimeType{Type = ".jar",Mime = "application/java-archive"},
                    new MimeType{Type = ".java",Mime = "text/x-java-source,java"},
                    new MimeType{Type = ".jck",Mime = "application/liquidmotion"},
                    new MimeType{Type = ".jcz",Mime = "application/liquidmotion"},
                    new MimeType{Type = ".jfif",Mime = "image/pjpeg"},
                    new MimeType{Type = ".jisp",Mime = "application/vnd.jisp"},
                    new MimeType{Type = ".jlt",Mime = "application/vnd.hp-jlyt"},
                    new MimeType{Type = ".jnlp",Mime = "application/x-java-jnlp-file"},
                    new MimeType{Type = ".joda",Mime = "application/vnd.joost.joda-archive"},
                    new MimeType{Type = ".jpb",Mime = "application/octet-stream"},
                    new MimeType{Type = ".jpe",Mime = "image/jpeg"},
                    new MimeType{Type = ".jpeg",Mime = "image/jpeg"},
                    new MimeType{Type = ".jpg",Mime = "image/jpeg"},
                    new MimeType{Type = ".jpgv",Mime = "video/jpeg"},
                    new MimeType{Type = ".jpm",Mime = "video/jpm"},
                    new MimeType{Type = ".js",Mime = "application/javascript"},
                    new MimeType{Type = ".json",Mime = "application/json"},
                    new MimeType{Type = ".jsonld",Mime = "application/ld+json"},
                    new MimeType{Type = ".jsx",Mime = "text/jscript"},
                    new MimeType{Type = ".karbon",Mime = "application/vnd.kde.karbon"},
                    new MimeType{Type = ".kfo",Mime = "application/vnd.kde.kformula"},
                    new MimeType{Type = ".kia",Mime = "application/vnd.kidspiration"},
                    new MimeType{Type = ".kml",Mime = "application/vnd.google-earth.kml+xml"},
                    new MimeType{Type = ".kmz",Mime = "application/vnd.google-earth.kmz"},
                    new MimeType{Type = ".kne",Mime = "application/vnd.kinar"},
                    new MimeType{Type = ".kon",Mime = "application/vnd.kde.kontour"},
                    new MimeType{Type = ".kpr",Mime = "application/vnd.kde.kpresenter"},
                    new MimeType{Type = ".ksp",Mime = "application/vnd.kde.kspread"},
                    new MimeType{Type = ".ktx",Mime = "image/ktx"},
                    new MimeType{Type = ".ktz",Mime = "application/vnd.kahootz"},
                    new MimeType{Type = ".kwd",Mime = "application/vnd.kde.kword"},
                    new MimeType{Type = ".lasxml",Mime = "application/vnd.las.las+xml"},
                    new MimeType{Type = ".latex",Mime = "application/x-latex"},
                    new MimeType{Type = ".lbd",Mime = "application/vnd.llamagraphics.life-balance.desktop"},
                    new MimeType{Type = ".lbe",Mime = "application/vnd.llamagraphics.life-balance.exchange+xml"},
                    new MimeType{Type = ".les",Mime = "application/vnd.hhe.lesson-player"},
                    new MimeType{Type = ".less",Mime = "text/css"},
                    new MimeType{Type = ".link66",Mime = "application/vnd.route66.link66+xml"},
                    new MimeType{Type = ".lit",Mime = "application/x-ms-reader"},
                    new MimeType{Type = ".lpk",Mime = "application/octet-stream"},
                    new MimeType{Type = ".lrm",Mime = "application/vnd.ms-lrm"},
                    new MimeType{Type = ".lsf",Mime = "video/x-la-asf"},
                    new MimeType{Type = ".lsx",Mime = "video/x-la-asf"},
                    new MimeType{Type = ".ltf",Mime = "application/vnd.frogans.ltf"},
                    new MimeType{Type = ".lvp",Mime = "audio/vnd.lucent.voice"},
                    new MimeType{Type = ".lwp",Mime = "application/vnd.lotus-wordpro"},
                    new MimeType{Type = ".lzh",Mime = "application/octet-stream"},
                    new MimeType{Type = ".m13",Mime = "application/x-msmediaview"},
                    new MimeType{Type = ".m14",Mime = "application/x-msmediaview"},
                    new MimeType{Type = ".m1v",Mime = "video/mpeg"},
                    new MimeType{Type = ".m21",Mime = "application/mp21"},
                    new MimeType{Type = ".m2ts",Mime = "video/vnd.dlna.mpeg-tts"},
                    new MimeType{Type = ".m3u",Mime = "audio/x-mpegurl"},
                    new MimeType{Type = ".m3u8",Mime = "application/vnd.apple.mpegurl"},
                    new MimeType{Type = ".m4a",Mime = "audio/mp4"},
                    new MimeType{Type = ".m4v",Mime = "video/mp4"},
                    new MimeType{Type = ".ma",Mime = "application/mathematica"},
                    new MimeType{Type = ".mads",Mime = "application/mads+xml"},
                    new MimeType{Type = ".mag",Mime = "application/vnd.ecowin.chart"},
                    new MimeType{Type = ".man",Mime = "application/x-troff-man"},
                    new MimeType{Type = ".manifest",Mime = "application/x-ms-manifest"},
                    new MimeType{Type = ".map",Mime = "text/plain"},
                    new MimeType{Type = ".mathml",Mime = "application/mathml+xml"},
                    new MimeType{Type = ".mbk",Mime = "application/vnd.mobius.mbk"},
                    new MimeType{Type = ".mbox",Mime = "application/mbox"},
                    new MimeType{Type = ".mc1",Mime = "application/vnd.medcalcdata"},
                    new MimeType{Type = ".mcd",Mime = "application/vnd.mcd"},
                    new MimeType{Type = ".mcurl",Mime = "text/vnd.curl.mcurl"},
                    new MimeType{Type = ".mdb",Mime = "application/x-msaccess"},
                    new MimeType{Type = ".mdi",Mime = "image/vnd.ms-modi"},
                    new MimeType{Type = ".mdp",Mime = "application/octet-stream"},
                    new MimeType{Type = ".me",Mime = "application/x-troff-me"},
                    new MimeType{Type = ".meta4",Mime = "application/metalink4+xml"},
                    new MimeType{Type = ".mets",Mime = "application/mets+xml"},
                    new MimeType{Type = ".mfm",Mime = "application/vnd.mfmp"},
                    new MimeType{Type = ".mgp",Mime = "application/vnd.osgeo.mapguide.package"},
                    new MimeType{Type = ".mgz",Mime = "application/vnd.proteus.magazine"},
                    new MimeType{Type = ".mht",Mime = "message/rfc822"},
                    new MimeType{Type = ".mhtml",Mime = "message/rfc822"},
                    new MimeType{Type = ".mid",Mime = "audio/x-midi"},
                    new MimeType{Type = ".midi",Mime = "audio/x-midi"},
                    new MimeType{Type = ".mif",Mime = "application/vnd.mif"},
                    new MimeType{Type = ".mix",Mime = "application/octet-stream"},
                    new MimeType{Type = ".mj2",Mime = "video/mj2"},
                    new MimeType{Type = ".mjs",Mime = "text/javascript"},
                    new MimeType{Type = ".mlp",Mime = "application/vnd.dolby.mlp"},
                    new MimeType{Type = ".mmd",Mime = "application/vnd.chipnuts.karaoke-mmd"},
                    new MimeType{Type = ".mmf",Mime = "application/x-smaf"},
                    new MimeType{Type = ".mmr",Mime = "image/vnd.fujixerox.edmics-mmr"},
                    new MimeType{Type = ".mno",Mime = "text/xml"},
                    new MimeType{Type = ".mny",Mime = "application/x-msmoney"},
                    new MimeType{Type = ".mods",Mime = "application/mods+xml"},
                    new MimeType{Type = ".mov",Mime = "video/quicktime"},
                    new MimeType{Type = ".movie",Mime = "video/x-sgi-movie"},
                    new MimeType{Type = ".mp2",Mime = "video/mpeg"},
                    new MimeType{Type = ".mp3",Mime = "audio/mpeg"},
                    new MimeType{Type = ".mp4",Mime = "video/mp4"},
                    new MimeType{Type = ".mp4a",Mime = "audio/mp4"},
                    new MimeType{Type = ".mp4v",Mime = "video/mp4"},
                    new MimeType{Type = ".mpa",Mime = "video/mpeg"},
                    new MimeType{Type = ".mpc",Mime = "application/vnd.mophun.certificate"},
                    new MimeType{Type = ".mpe",Mime = "video/mpeg"},
                    new MimeType{Type = ".mpeg",Mime = "video/mpeg"},
                    new MimeType{Type = ".mpg",Mime = "video/mpeg"},
                    new MimeType{Type = ".mpga",Mime = "audio/mpeg"},
                    new MimeType{Type = ".mpkg",Mime = "application/vnd.apple.installer+xml"},
                    new MimeType{Type = ".mpm",Mime = "application/vnd.blueice.multipass"},
                    new MimeType{Type = ".mpn",Mime = "application/vnd.mophun.application"},
                    new MimeType{Type = ".mpp",Mime = "application/vnd.ms-project"},
                    new MimeType{Type = ".mpv2",Mime = "video/mpeg"},
                    new MimeType{Type = ".mpy",Mime = "application/vnd.ibm.minipay"},
                    new MimeType{Type = ".mqy",Mime = "application/vnd.mobius.mqy"},
                    new MimeType{Type = ".mrc",Mime = "application/marc"},
                    new MimeType{Type = ".mrcx",Mime = "application/marcxml+xml"},
                    new MimeType{Type = ".ms",Mime = "application/x-troff-ms"},
                    new MimeType{Type = ".mscml",Mime = "application/mediaservercontrol+xml"},
                    new MimeType{Type = ".mseq",Mime = "application/vnd.mseq"},
                    new MimeType{Type = ".msf",Mime = "application/vnd.epson.msf"},
                    new MimeType{Type = ".msh",Mime = "model/mesh"},
                    new MimeType{Type = ".msi",Mime = "application/octet-stream"},
                    new MimeType{Type = ".msl",Mime = "application/vnd.mobius.msl"},
                    new MimeType{Type = ".mso",Mime = "application/octet-stream"},
                    new MimeType{Type = ".msty",Mime = "application/vnd.muvee.style"},
                    new MimeType{Type = ".mts",Mime = "model/vnd.mts"},
                    new MimeType{Type = ".mus",Mime = "application/vnd.musician"},
                    new MimeType{Type = ".musicxml",Mime = "application/vnd.recordare.musicxml+xml"},
                    new MimeType{Type = ".mvb",Mime = "application/x-msmediaview"},
                    new MimeType{Type = ".mvc",Mime = "application/x-miva-compiled"},
                    new MimeType{Type = ".mwf",Mime = "application/vnd.mfer"},
                    new MimeType{Type = ".mxf",Mime = "application/mxf"},
                    new MimeType{Type = ".mxl",Mime = "application/vnd.recordare.musicxml"},
                    new MimeType{Type = ".mxml",Mime = "application/xv+xml"},
                    new MimeType{Type = ".mxs",Mime = "application/vnd.triscape.mxs"},
                    new MimeType{Type = ".mxu",Mime = "video/vnd.mpegurl"},
                    new MimeType{Type = ".N/A",Mime = "application/andrew-inset"},
                    new MimeType{Type = ".n3",Mime = "text/n3"},
                    new MimeType{Type = ".nbp",Mime = "application/vnd.wolfram.player"},
                    new MimeType{Type = ".nc",Mime = "application/x-netcdf"},
                    new MimeType{Type = ".ncx",Mime = "application/x-dtbncx+xml"},
                    new MimeType{Type = ".n-gage",Mime = "application/vnd.nokia.n-gage.symbian.install"},
                    new MimeType{Type = ".ngdat",Mime = "application/vnd.nokia.n-gage.data"},
                    new MimeType{Type = ".nlu",Mime = "application/vnd.neurolanguage.nlu"},
                    new MimeType{Type = ".nml",Mime = "application/vnd.enliven"},
                    new MimeType{Type = ".nnd",Mime = "application/vnd.noblenet-directory"},
                    new MimeType{Type = ".nns",Mime = "application/vnd.noblenet-sealer"},
                    new MimeType{Type = ".nnw",Mime = "application/vnd.noblenet-web"},
                    new MimeType{Type = ".npx",Mime = "image/vnd.net-fpx"},
                    new MimeType{Type = ".nsc",Mime = "video/x-ms-asf"},
                    new MimeType{Type = ".nsf",Mime = "application/vnd.lotus-notes"},
                    new MimeType{Type = ".nws",Mime = "message/rfc822"},
                    new MimeType{Type = ".oa2",Mime = "application/vnd.fujitsu.oasys2"},
                    new MimeType{Type = ".oa3",Mime = "application/vnd.fujitsu.oasys3"},
                    new MimeType{Type = ".oas",Mime = "application/vnd.fujitsu.oasys"},
                    new MimeType{Type = ".obd",Mime = "application/x-msbinder"},
                    new MimeType{Type = ".ocx",Mime = "application/octet-stream"},
                    new MimeType{Type = ".oda",Mime = "application/oda"},
                    new MimeType{Type = ".odb",Mime = "application/vnd.oasis.opendocument.database"},
                    new MimeType{Type = ".odc",Mime = "text/x-ms-odc"},
                    new MimeType{Type = ".odf",Mime = "application/vnd.oasis.opendocument.formula"},
                    new MimeType{Type = ".odft",Mime = "application/vnd.oasis.opendocument.formula-template"},
                    new MimeType{Type = ".odg",Mime = "application/vnd.oasis.opendocument.graphics"},
                    new MimeType{Type = ".odi",Mime = "application/vnd.oasis.opendocument.image"},
                    new MimeType{Type = ".odm",Mime = "application/vnd.oasis.opendocument.text-master"},
                    new MimeType{Type = ".odp",Mime = "application/vnd.oasis.opendocument.presentation"},
                    new MimeType{Type = ".ods",Mime = "application/oleobject"},
                    new MimeType{Type = ".odt",Mime = "application/vnd.oasis.opendocument.text"},
                    new MimeType{Type = ".oga",Mime = "audio/ogg"},
                    new MimeType{Type = ".ogg",Mime = "video/ogg"},
                    new MimeType{Type = ".ogv",Mime = "video/ogg"},
                    new MimeType{Type = ".ogx",Mime = "application/ogg"},
                    new MimeType{Type = ".one",Mime = "application/onenote"},
                    new MimeType{Type = ".onea",Mime = "application/onenote"},
                    new MimeType{Type = ".onepkg",Mime = "application/onenote"},
                    new MimeType{Type = ".onetmp",Mime = "application/onenote"},
                    new MimeType{Type = ".onetoc",Mime = "application/onenote"},
                    new MimeType{Type = ".onetoc2",Mime = "application/onenote"},
                    new MimeType{Type = ".opf",Mime = "application/oebps-package+xml"},
                    new MimeType{Type = ".org",Mime = "application/vnd.lotus-organizer"},
                    new MimeType{Type = ".osdx",Mime = "application/opensearchdescription+xml"},
                    new MimeType{Type = ".osf",Mime = "application/vnd.yamaha.openscoreformat"},
                    new MimeType{Type = ".osfpvg",Mime = "application/vnd.yamaha.openscoreformat.osfpvg+xml"},
                    new MimeType{Type = ".otc",Mime = "application/vnd.oasis.opendocument.chart-template"},
                    new MimeType{Type = ".otf",Mime = "font/otf"},
                    new MimeType{Type = ".otg",Mime = "application/vnd.oasis.opendocument.graphics-template"},
                    new MimeType{Type = ".oth",Mime = "application/vnd.oasis.opendocument.text-web"},
                    new MimeType{Type = ".oti",Mime = "application/vnd.oasis.opendocument.image-template"},
                    new MimeType{Type = ".otp",Mime = "application/vnd.oasis.opendocument.presentation-template"},
                    new MimeType{Type = ".ots",Mime = "application/vnd.oasis.opendocument.spreadsheet-template"},
                    new MimeType{Type = ".ott",Mime = "application/vnd.oasis.opendocument.text-template"},
                    new MimeType{Type = ".oxt",Mime = "application/vnd.openofficeorg.extension"},
                    new MimeType{Type = ".p",Mime = "text/x-pascal"},
                    new MimeType{Type = ".p10",Mime = "application/pkcs10"},
                    new MimeType{Type = ".p12",Mime = "application/x-pkcs12"},
                    new MimeType{Type = ".p7b",Mime = "application/x-pkcs7-certificates"},
                    new MimeType{Type = ".p7c",Mime = "application/pkcs7-mime"},
                    new MimeType{Type = ".p7m",Mime = "application/pkcs7-mime"},
                    new MimeType{Type = ".p7r",Mime = "application/x-pkcs7-certreqresp"},
                    new MimeType{Type = ".p7s",Mime = "application/pkcs7-signature"},
                    new MimeType{Type = ".p8",Mime = "application/pkcs8"},
                    new MimeType{Type = ".par",Mime = "text/plain-bas"},
                    new MimeType{Type = ".paw",Mime = "application/vnd.pawaafile"},
                    new MimeType{Type = ".pbd",Mime = "application/vnd.powerbuilder6"},
                    new MimeType{Type = ".pbm",Mime = "image/x-portable-bitmap"},
                    new MimeType{Type = ".pcf",Mime = "application/x-font-pcf"},
                    new MimeType{Type = ".pcl",Mime = "application/vnd.hp-pcl"},
                    new MimeType{Type = ".pclxl",Mime = "application/vnd.hp-pclxl"},
                    new MimeType{Type = ".pcurl",Mime = "application/vnd.curl.pcurl"},
                    new MimeType{Type = ".pcx",Mime = "image/x-pcx"},
                    new MimeType{Type = ".pcz",Mime = "application/octet-stream"},
                    new MimeType{Type = ".pdb",Mime = "application/vnd.palm"},
                    new MimeType{Type = ".pdf",Mime = "application/pdf"},
                    new MimeType{Type = ".pfa",Mime = "application/x-font-type1"},
                    new MimeType{Type = ".pfb",Mime = "application/octet-stream"},
                    new MimeType{Type = ".pfm",Mime = "application/octet-stream"},
                    new MimeType{Type = ".pfr",Mime = "application/font-tdpfr"},
                    new MimeType{Type = ".pfx",Mime = "application/x-pkcs12"},
                    new MimeType{Type = ".pgm",Mime = "image/x-portable-graymap"},
                    new MimeType{Type = ".pgn",Mime = "application/x-chess-pgn"},
                    new MimeType{Type = ".pgp",Mime = "application/pgp-signature"},
                    new MimeType{Type = ".pic",Mime = "image/x-pict"},
                    new MimeType{Type = ".pjpeg",Mime = "image/pjpeg"},
                    new MimeType{Type = ".pki",Mime = "application/pkixcmp"},
                    new MimeType{Type = ".pkipath",Mime = "application/pkix-pkipath"},
                    new MimeType{Type = ".pko",Mime = "application/vnd.ms-pki.pko"},
                    new MimeType{Type = ".plb",Mime = "application/vnd.3gpp.pic-bw-large"},
                    new MimeType{Type = ".plc",Mime = "application/vnd.mobius.plc"},
                    new MimeType{Type = ".plf",Mime = "application/vnd.pocketlearn"},
                    new MimeType{Type = ".pls",Mime = "application/pls+xml"},
                    new MimeType{Type = ".pma",Mime = "application/x-perfmon"},
                    new MimeType{Type = ".pmc",Mime = "application/x-perfmon"},
                    new MimeType{Type = ".pml",Mime = "application/x-perfmon"},
                    new MimeType{Type = ".pmr",Mime = "application/x-perfmon"},
                    new MimeType{Type = ".pmw",Mime = "application/x-perfmon"},
                    new MimeType{Type = ".png",Mime = "image/png"},
                    new MimeType{Type = ".pnm",Mime = "image/x-portable-anymap"},
                    new MimeType{Type = ".pnz",Mime = "image/png"},
                    new MimeType{Type = ".portpkg",Mime = "application/vnd.macports.portpkg"},
                    new MimeType{Type = ".pot",Mime = "application/vnd.ms-powerpoint"},
                    new MimeType{Type = ".potm",Mime = "application/vnd.ms-powerpoint.template.macroEnabled.12"},
                    new MimeType{Type = ".potx",Mime = "application/vnd.openxmlformats-officedocument.presentationml.template"},
                    new MimeType{Type = ".ppam",Mime = "application/vnd.ms-powerpoint.addin.macroEnabled.12"},
                    new MimeType{Type = ".ppd",Mime = "application/vnd.cups-ppd"},
                    new MimeType{Type = ".ppm",Mime = "image/x-portable-pixmap"},
                    new MimeType{Type = ".pps",Mime = "application/vnd.ms-powerpoint"},
                    new MimeType{Type = ".ppsm",Mime = "application/vnd.ms-powerpoint.slideshow.macroEnabled.12"},
                    new MimeType{Type = ".ppsx",Mime = "application/vnd.openxmlformats-officedocument.presentationml.slideshow"},
                    new MimeType{Type = ".ppt",Mime = "application/vnd.ms-powerpoint"},
                    new MimeType{Type = ".pptm",Mime = "application/vnd.ms-powerpoint.presentation.macroEnabled.12"},
                    new MimeType{Type = ".pptx",Mime = "application/vnd.openxmlformats-officedocument.presentationml.presentation"},
                    new MimeType{Type = ".prc",Mime = "application/x-mobipocket-ebook"},
                    new MimeType{Type = ".pre",Mime = "application/vnd.lotus-freelance"},
                    new MimeType{Type = ".prf",Mime = "application/pics-rules"},
                    new MimeType{Type = ".prm",Mime = "application/octet-stream"},
                    new MimeType{Type = ".prx",Mime = "application/octet-stream"},
                    new MimeType{Type = ".ps",Mime = "application/postscript"},
                    new MimeType{Type = ".psb",Mime = "application/vnd.3gpp.pic-bw-small"},
                    new MimeType{Type = ".psd",Mime = "image/vnd.adobe.photoshop"},
                    new MimeType{Type = ".psf",Mime = "application/x-font-linux-psf"},
                    new MimeType{Type = ".pskcxml",Mime = "application/pskc+xml"},
                    new MimeType{Type = ".psm",Mime = "application/octet-stream"},
                    new MimeType{Type = ".psp",Mime = "application/octet-stream"},
                    new MimeType{Type = ".ptid",Mime = "application/vnd.pvi.ptid1"},
                    new MimeType{Type = ".pub",Mime = "application/x-mspublisher"},
                    new MimeType{Type = ".pvb",Mime = "application/vnd.3gpp.pic-bw-var"},
                    new MimeType{Type = ".pwn",Mime = "application/vnd.3m.post-it-notes"},
                    new MimeType{Type = ".pya",Mime = "audio/vnd.ms-playready.media.pya"},
                    new MimeType{Type = ".pyv",Mime = "video/vnd.ms-playready.media.pyv"},
                    new MimeType{Type = ".qam",Mime = "application/vnd.epson.quickanime"},
                    new MimeType{Type = ".qbo",Mime = "application/vnd.intu.qbo"},
                    new MimeType{Type = ".qfx",Mime = "application/vnd.intu.qfx"},
                    new MimeType{Type = ".qps",Mime = "application/vnd.publishare-delta-tree"},
                    new MimeType{Type = ".qt",Mime = "video/quicktime"},
                    new MimeType{Type = ".qtl",Mime = "application/x-quicktimeplayer"},
                    new MimeType{Type = ".qxd",Mime = "application/vnd.quark.quarkxpress"},
                    new MimeType{Type = ".ra",Mime = "audio/x-pn-realaudio"},
                    new MimeType{Type = ".ram",Mime = "audio/x-pn-realaudio"},
                    new MimeType{Type = ".rar",Mime = "application/x-rar-compressed"},
                    new MimeType{Type = ".ras",Mime = "image/x-cmu-raster"},
                    new MimeType{Type = ".rcprofile",Mime = "application/vnd.ipunplugged.rcprofile"},
                    new MimeType{Type = ".rdf",Mime = "application/rdf+xml"},
                    new MimeType{Type = ".rdz",Mime = "application/vnd.data-vision.rdz"},
                    new MimeType{Type = ".rep",Mime = "application/vnd.businessobjects"},
                    new MimeType{Type = ".res",Mime = "application/x-dtbresource+xml"},
                    new MimeType{Type = ".rf",Mime = "image/vnd.rn-realflash"},
                    new MimeType{Type = ".rgb",Mime = "image/x-rgb"},
                    new MimeType{Type = ".rif",Mime = "application/reginfo+xml"},
                    new MimeType{Type = ".rip",Mime = "audio/vnd.rip"},
                    new MimeType{Type = ".rl",Mime = "application/resource-lists+xml"},
                    new MimeType{Type = ".rlc",Mime = "image/vnd.fujixerox.edmics-rlc"},
                    new MimeType{Type = ".rld",Mime = "application/resource-lists-diff+xml"},
                    new MimeType{Type = ".rm",Mime = "application/vnd.rn-realmedia"},
                    new MimeType{Type = ".rmi",Mime = "audio/mid"},
                    new MimeType{Type = ".rmp",Mime = "audio/x-pn-realaudio-plugin"},
                    new MimeType{Type = ".rms",Mime = "application/vnd.jcp.javame.midlet-rms"},
                    new MimeType{Type = ".rnc",Mime = "application/relax-ng-compact-syntax"},
                    new MimeType{Type = ".roff",Mime = "application/x-troff"},
                    new MimeType{Type = ".rp9",Mime = "application/vnd.cloanto.rp9"},
                    new MimeType{Type = ".rpm",Mime = "audio/x-pn-realaudio-plugin"},
                    new MimeType{Type = ".rpss",Mime = "application/vnd.nokia.radio-presets"},
                    new MimeType{Type = ".rpst",Mime = "application/vnd.nokia.radio-preset"},
                    new MimeType{Type = ".rq",Mime = "application/sparql-query"},
                    new MimeType{Type = ".rs",Mime = "application/rls-services+xml"},
                    new MimeType{Type = ".rsd",Mime = "application/rsd+xml"},
                    new MimeType{Type = ".rss",Mime = "application/rss+xml"},
                    new MimeType{Type = ".rtf",Mime = "application/rtf"},
                    new MimeType{Type = ".rtx",Mime = "text/richtext"},
                    new MimeType{Type = ".s",Mime = "text/x-asm"},
                    new MimeType{Type = ".saf",Mime = "application/vnd.yamaha.smaf-audio"},
                    new MimeType{Type = ".sbml",Mime = "application/sbml+xml"},
                    new MimeType{Type = ".sc",Mime = "application/vnd.ibm.secure-container"},
                    new MimeType{Type = ".scd",Mime = "application/x-msschedule"},
                    new MimeType{Type = ".scm",Mime = "application/vnd.lotus-screencam"},
                    new MimeType{Type = ".scq",Mime = "application/scvp-cv-request"},
                    new MimeType{Type = ".scs",Mime = "application/scvp-cv-response"},
                    new MimeType{Type = ".sct",Mime = "text/scriptlet"},
                    new MimeType{Type = ".scurl",Mime = "text/vnd.curl.scurl"},
                    new MimeType{Type = ".sda",Mime = "application/vnd.stardivision.draw"},
                    new MimeType{Type = ".sdc",Mime = "application/vnd.stardivision.calc"},
                    new MimeType{Type = ".sdd",Mime = "application/vnd.stardivision.impress"},
                    new MimeType{Type = ".sdkm",Mime = "application/vnd.solent.sdkm+xml"},
                    new MimeType{Type = ".sdp",Mime = "application/sdp"},
                    new MimeType{Type = ".sdw",Mime = "application/vnd.stardivision.writer"},
                    new MimeType{Type = ".sea",Mime = "application/octet-stream"},
                    new MimeType{Type = ".see",Mime = "application/vnd.seemail"},
                    new MimeType{Type = ".seed",Mime = "application/vnd.fdsn.seed"},
                    new MimeType{Type = ".sema",Mime = "application/vnd.sema"},
                    new MimeType{Type = ".semd",Mime = "application/vnd.semd"},
                    new MimeType{Type = ".semf",Mime = "application/vnd.semf"},
                    new MimeType{Type = ".ser",Mime = "application/java-serialized-object"},
                    new MimeType{Type = ".setpay",Mime = "application/set-payment-initiation"},
                    new MimeType{Type = ".setreg",Mime = "application/set-registration-initiation"},
                    new MimeType{Type = ".sfd-hdstx",Mime = "application/vnd.hydrostatix.sof-data"},
                    new MimeType{Type = ".sfs",Mime = "application/vnd.spotfire.sfs"},
                    new MimeType{Type = ".sgl",Mime = "application/vnd.stardivision.writer-global"},
                    new MimeType{Type = ".sgml",Mime = "text/sgml"},
                    new MimeType{Type = ".sh",Mime = "application/x-sh"},
                    new MimeType{Type = ".shar",Mime = "application/x-shar"},
                    new MimeType{Type = ".shf",Mime = "application/shf+xml"},
                    new MimeType{Type = ".sis",Mime = "application/vnd.symbian.install"},
                    new MimeType{Type = ".sit",Mime = "application/x-stuffit"},
                    new MimeType{Type = ".sitx",Mime = "application/x-stuffitx"},
                    new MimeType{Type = ".skp",Mime = "application/vnd.koan"},
                    new MimeType{Type = ".sldm",Mime = "application/vnd.ms-powerpoint.slide.macroEnabled.12"},
                    new MimeType{Type = ".sldx",Mime = "application/vnd.openxmlformats-officedocument.presentationml.slide"},
                    new MimeType{Type = ".slt",Mime = "application/vnd.epson.salt"},
                    new MimeType{Type = ".sm",Mime = "application/vnd.stepmania.stepchart"},
                    new MimeType{Type = ".smd",Mime = "audio/x-smd"},
                    new MimeType{Type = ".smf",Mime = "application/vnd.stardivision.math"},
                    new MimeType{Type = ".smi",Mime = "application/smil+xml"},
                    new MimeType{Type = ".smx",Mime = "audio/x-smd"},
                    new MimeType{Type = ".smz",Mime = "audio/x-smd"},
                    new MimeType{Type = ".snd",Mime = "audio/basic"},
                    new MimeType{Type = ".snf",Mime = "application/x-font-snf"},
                    new MimeType{Type = ".snp",Mime = "application/octet-stream"},
                    new MimeType{Type = ".spc",Mime = "application/x-pkcs7-certificates"},
                    new MimeType{Type = ".spf",Mime = "application/vnd.yamaha.smaf-phrase"},
                    new MimeType{Type = ".spl",Mime = "application/futuresplash"},
                    new MimeType{Type = ".spot",Mime = "text/vnd.in3d.spot"},
                    new MimeType{Type = ".spp",Mime = "application/scvp-vp-response"},
                    new MimeType{Type = ".spq",Mime = "application/scvp-vp-request"},
                    new MimeType{Type = ".spx",Mime = "audio/ogg"},
                    new MimeType{Type = ".src",Mime = "application/x-wais-source"},
                    new MimeType{Type = ".sru",Mime = "application/sru+xml"},
                    new MimeType{Type = ".srx",Mime = "application/sparql-results+xml"},
                    new MimeType{Type = ".sse",Mime = "application/vnd.kodak-descriptor"},
                    new MimeType{Type = ".ssf",Mime = "application/vnd.epson.ssf"},
                    new MimeType{Type = ".ssm",Mime = "application/streamingmedia"},
                    new MimeType{Type = ".ssml",Mime = "application/ssml+xml"},
                    new MimeType{Type = ".sst",Mime = "application/vnd.ms-pki.certstore"},
                    new MimeType{Type = ".st",Mime = "application/vnd.sailingtracker.track"},
                    new MimeType{Type = ".stc",Mime = "application/vnd.sun.xml.calc.template"},
                    new MimeType{Type = ".std",Mime = "application/vnd.sun.xml.draw.template"},
                    new MimeType{Type = ".stf",Mime = "application/vnd.wt.stf"},
                    new MimeType{Type = ".sti",Mime = "application/vnd.sun.xml.impress.template"},
                    new MimeType{Type = ".stk",Mime = "application/hyperstudio"},
                    new MimeType{Type = ".stl",Mime = "application/vnd.ms-pki.stl"},
                    new MimeType{Type = ".str",Mime = "application/vnd.pg.format"},
                    new MimeType{Type = ".stw",Mime = "application/vnd.sun.xml.writer.template"},
                    new MimeType{Type = ".sub",Mime = "image/vnd.dvb.subtitle"},
                    new MimeType{Type = ".sus",Mime = "application/vnd.sus-calendar"},
                    new MimeType{Type = ".sv4cpio",Mime = "application/x-sv4cpio"},
                    new MimeType{Type = ".sv4crc",Mime = "application/x-sv4crc"},
                    new MimeType{Type = ".svc",Mime = "application/vnd.dvb.service"},
                    new MimeType{Type = ".svd",Mime = "application/vnd.svd"},
                    new MimeType{Type = ".svg",Mime = "image/svg+xml"},
                    new MimeType{Type = ".svgz",Mime = "image/svg+xml"},
                    new MimeType{Type = ".swf",Mime = "application/x-shockwave-flash"},
                    new MimeType{Type = ".swi",Mime = "application/vnd.aristanetworks.swi"},
                    new MimeType{Type = ".sxc",Mime = "application/vnd.sun.xml.calc"},
                    new MimeType{Type = ".sxd",Mime = "application/vnd.sun.xml.draw"},
                    new MimeType{Type = ".sxg",Mime = "application/vnd.sun.xml.writer.global"},
                    new MimeType{Type = ".sxi",Mime = "application/vnd.sun.xml.impress"},
                    new MimeType{Type = ".sxm",Mime = "application/vnd.sun.xml.math"},
                    new MimeType{Type = ".sxw",Mime = "application/vnd.sun.xml.writer"},
                    new MimeType{Type = ".t",Mime = "application/x-troff"},
                    new MimeType{Type = ".tao",Mime = "application/vnd.tao.intent-module-archive"},
                    new MimeType{Type = ".tar",Mime = "application/x-tar"},
                    new MimeType{Type = ".tcap",Mime = "application/vnd.3gpp2.tcap"},
                    new MimeType{Type = ".tcl",Mime = "application/x-tcl"},
                    new MimeType{Type = ".teacher",Mime = "application/vnd.smart.teacher"},
                    new MimeType{Type = ".tei",Mime = "application/tei+xml"},
                    new MimeType{Type = ".tex",Mime = "application/x-tex"},
                    new MimeType{Type = ".texi",Mime = "application/x-texinfo"},
                    new MimeType{Type = ".texinfo",Mime = "application/x-texinfo"},
                    new MimeType{Type = ".tfi",Mime = "application/thraud+xml"},
                    new MimeType{Type = ".tfm",Mime = "application/x-tex-tfm"},
                    new MimeType{Type = ".tgz",Mime = "application/x-compressed"},
                    new MimeType{Type = ".thmx",Mime = "application/vnd.ms-officetheme"},
                    new MimeType{Type = ".thn",Mime = "application/octet-stream"},
                    new MimeType{Type = ".tif",Mime = "image/tiff"},
                    new MimeType{Type = ".tif",Mime = "image/tiff"},
                    new MimeType{Type = ".tiff",Mime = "image/tiff"},
                    new MimeType{Type = ".tmo",Mime = "application/vnd.tmobile-livetv"},
                    new MimeType{Type = ".toc",Mime = "application/octet-stream"},
                    new MimeType{Type = ".torrent",Mime = "application/x-bittorrent"},
                    new MimeType{Type = ".tpl",Mime = "application/vnd.groove-tool-template"},
                    new MimeType{Type = ".tpt",Mime = "application/vnd.trid.tpt"},
                    new MimeType{Type = ".tr",Mime = "application/x-troff"},
                    new MimeType{Type = ".tra",Mime = "application/vnd.trueapp"},
                    new MimeType{Type = ".trm",Mime = "application/x-msterminal"},
                    new MimeType{Type = ".ts",Mime = "video/mp2t"},
                    new MimeType{Type = ".tsd",Mime = "application/timestamped-data"},
                    new MimeType{Type = ".tsv",Mime = "text/tab-separated-values"},
                    new MimeType{Type = ".ttf",Mime = " font/ttf"},
                    new MimeType{Type = ".ttl",Mime = "text/turtle"},
                    new MimeType{Type = ".tts",Mime = "video/vnd.dlna.mpeg-tts"},
                    new MimeType{Type = ".twd",Mime = "application/vnd.simtech-mindmapper"},
                    new MimeType{Type = ".txd",Mime = "application/vnd.genomatix.tuxedo"},
                    new MimeType{Type = ".txf",Mime = "application/vnd.mobius.txf"},
                    new MimeType{Type = ".txt",Mime = "text/plain"},
                    new MimeType{Type = ".u32",Mime = "application/octet-stream"},
                    new MimeType{Type = ".ufd",Mime = "application/vnd.ufdl"},
                    new MimeType{Type = ".uls",Mime = "text/iuls"},
                    new MimeType{Type = ".umj",Mime = "application/vnd.umajin"},
                    new MimeType{Type = ".unityweb",Mime = "application/vnd.unity"},
                    new MimeType{Type = ".uoml",Mime = "application/vnd.uoml+xml"},
                    new MimeType{Type = ".uri",Mime = "text/uri-list"},
                    new MimeType{Type = ".ustar",Mime = "application/x-ustar"},
                    new MimeType{Type = ".utz",Mime = "application/vnd.uiq.theme"},
                    new MimeType{Type = ".uu",Mime = "text/x-uuencode"},
                    new MimeType{Type = ".uva",Mime = "audio/vnd.dece.audio"},
                    new MimeType{Type = ".uvh",Mime = "video/vnd.dece.hd"},
                    new MimeType{Type = ".uvi",Mime = "image/vnd.dece.graphic"},
                    new MimeType{Type = ".uvm",Mime = "video/vnd.dece.mobile"},
                    new MimeType{Type = ".uvp",Mime = "video/vnd.dece.pd"},
                    new MimeType{Type = ".uvs",Mime = "video/vnd.dece.sd"},
                    new MimeType{Type = ".uvu",Mime = "video/vnd.uvvu.mp4"},
                    new MimeType{Type = ".uvv",Mime = "video/vnd.dece.video"},
                    new MimeType{Type = ".vbs",Mime = "text/vbscript"},
                    new MimeType{Type = ".vcd",Mime = "application/x-cdlink"},
                    new MimeType{Type = ".vcf",Mime = "text/x-vcard"},
                    new MimeType{Type = ".vcg",Mime = "application/vnd.groove-vcard"},
                    new MimeType{Type = ".vcs",Mime = "text/x-vcalendar"},
                    new MimeType{Type = ".vcx",Mime = "application/vnd.vcx"},
                    new MimeType{Type = ".vdx",Mime = "application/vnd.ms-visio.viewer"},
                    new MimeType{Type = ".vis",Mime = "application/vnd.visionary"},
                    new MimeType{Type = ".viv",Mime = "video/vnd.vivo"},
                    new MimeType{Type = ".vml",Mime = "text/xml"},
                    new MimeType{Type = ".vsd",Mime = "application/vnd.visio"},
                    new MimeType{Type = ".vsdx",Mime = "application/vnd.visio2013"},
                    new MimeType{Type = ".vsf",Mime = "application/vnd.vsf"},
                    new MimeType{Type = ".vss",Mime = "application/vnd.visio"},
                    new MimeType{Type = ".vst",Mime = "application/vnd.visio"},
                    new MimeType{Type = ".vsto",Mime = "application/x-ms-vsto"},
                    new MimeType{Type = ".vsw",Mime = "application/vnd.visio"},
                    new MimeType{Type = ".vsx",Mime = "application/vnd.visio"},
                    new MimeType{Type = ".vtu",Mime = "model/vnd.vtu"},
                    new MimeType{Type = ".vtx",Mime = "application/vnd.visio"},
                    new MimeType{Type = ".vxml",Mime = "application/voicexml+xml"},
                    new MimeType{Type = ".wad",Mime = "application/x-doom"},
                    new MimeType{Type = ".wasm",Mime = "application/wasm"},
                    new MimeType{Type = ".wav",Mime = "audio/x-wav"},
                    new MimeType{Type = ".wax",Mime = "audio/x-ms-wax"},
                    new MimeType{Type = ".wbmp",Mime = "image/vnd.wap.wbmp"},
                    new MimeType{Type = ".wbs",Mime = "application/vnd.criticaltools.wbs+xml"},
                    new MimeType{Type = ".wbxml",Mime = "application/vnd.wap.wbxml"},
                    new MimeType{Type = ".wcm",Mime = "application/vnd.ms-works"},
                    new MimeType{Type = ".wdb",Mime = "application/vnd.ms-works"},
                    new MimeType{Type = ".weba",Mime = "audio/webm"},
                    new MimeType{Type = ".webm",Mime = "video/webm"},
                    new MimeType{Type = ".webp",Mime = "image/webp"},
                    new MimeType{Type = ".wg",Mime = "application/vnd.pmi.widget"},
                    new MimeType{Type = ".wgt",Mime = "application/widget"},
                    new MimeType{Type = ".wks",Mime = "application/vnd.ms-works"},
                    new MimeType{Type = ".wm",Mime = "video/x-ms-wm"},
                    new MimeType{Type = ".wma",Mime = "audio/x-ms-wma"},
                    new MimeType{Type = ".wmd",Mime = "application/x-ms-wmd"},
                    new MimeType{Type = ".wmf",Mime = "application/x-msmetafile"},
                    new MimeType{Type = ".wml",Mime = "text/vnd.wap.wml"},
                    new MimeType{Type = ".wmlc",Mime = "application/vnd.wap.wmlc"},
                    new MimeType{Type = ".wmls",Mime = "text/vnd.wap.wmlscript"},
                    new MimeType{Type = ".wmlsc",Mime = "application/vnd.wap.wmlscriptc"},
                    new MimeType{Type = ".wmp",Mime = "video/x-ms-wmp"},
                    new MimeType{Type = ".wmv",Mime = "video/x-ms-wmv"},
                    new MimeType{Type = ".wmx",Mime = "video/x-ms-wmx"},
                    new MimeType{Type = ".wmz",Mime = "application/x-ms-wmz"},
                    new MimeType{Type = ".woff",Mime = "font/woff"},
                    new MimeType{Type = ".woff2",Mime = "font/woff2"},
                    new MimeType{Type = ".woff2",Mime = "application/font-woff2"},
                    new MimeType{Type = ".wpd",Mime = "application/vnd.wordperfect"},
                    new MimeType{Type = ".wpl",Mime = "application/vnd.ms-wpl"},
                    new MimeType{Type = ".wps",Mime = "application/vnd.ms-works"},
                    new MimeType{Type = ".wqd",Mime = "application/vnd.wqd"},
                    new MimeType{Type = ".wri",Mime = "application/x-mswrite"},
                    new MimeType{Type = ".wrl",Mime = "x-world/x-vrml"},
                    new MimeType{Type = ".wrz",Mime = "x-world/x-vrml"},
                    new MimeType{Type = ".wsdl",Mime = "application/wsdl+xml"},
                    new MimeType{Type = ".wspolicy",Mime = "application/wspolicy+xml"},
                    new MimeType{Type = ".wtb",Mime = "application/vnd.webturbo"},
                    new MimeType{Type = ".wtv",Mime = "video/x-ms-wtv"},
                    new MimeType{Type = ".wvx",Mime = "video/x-ms-wvx"},
                    new MimeType{Type = ".x",Mime = "application/directx"},
                    new MimeType{Type = ".x3d",Mime = "application/vnd.hzn-3d-crossword"},
                    new MimeType{Type = ".xaf",Mime = "x-world/x-vrml"},
                    new MimeType{Type = ".xaml",Mime = "application/xaml+xml"},
                    new MimeType{Type = ".xap",Mime = "application/x-silverlight-app"},
                    new MimeType{Type = ".xar",Mime = "application/vnd.xara"},
                    new MimeType{Type = ".xbap",Mime = "application/x-ms-xbap"},
                    new MimeType{Type = ".xbd",Mime = "application/vnd.fujixerox.docuworks.binder"},
                    new MimeType{Type = ".xbm",Mime = "image/x-xbitmap"},
                    new MimeType{Type = ".xdf",Mime = "application/xcap-diff+xml"},
                    new MimeType{Type = ".xdm",Mime = "application/vnd.syncml.dm+xml"},
                    new MimeType{Type = ".xdp",Mime = "application/vnd.adobe.xdp+xml"},
                    new MimeType{Type = ".xdr",Mime = "text/plain"},
                    new MimeType{Type = ".xdssc",Mime = "application/dssc+xml"},
                    new MimeType{Type = ".xdw",Mime = "application/vnd.fujixerox.docuworks"},
                    new MimeType{Type = ".xenc",Mime = "application/xenc+xml"},
                    new MimeType{Type = ".xer",Mime = "application/patch-ops-error+xml"},
                    new MimeType{Type = ".xfdf",Mime = "application/vnd.adobe.xfdf"},
                    new MimeType{Type = ".xfdl",Mime = "application/vnd.xfdl"},
                    new MimeType{Type = ".xht",Mime = "application/xhtml+xml"},
                    new MimeType{Type = ".xhtml",Mime = "application/xhtml+xml"},
                    new MimeType{Type = ".xif",Mime = "image/vnd.xiff"},
                    new MimeType{Type = ".xla",Mime = "application/vnd.ms-excel"},
                    new MimeType{Type = ".xlam",Mime = "application/vnd.ms-excel.addin.macroEnabled.12"},
                    new MimeType{Type = ".xlc",Mime = "application/vnd.ms-excel"},
                    new MimeType{Type = ".xlm",Mime = "application/vnd.ms-excel"},
                    new MimeType{Type = ".xls",Mime = "application/vnd.ms-excel"},
                    new MimeType{Type = ".xlsb",Mime = "application/vnd.ms-excel.sheet.binary.macroEnabled.12"},
                    new MimeType{Type = ".xlsm",Mime = "application/vnd.ms-excel.sheet.macroEnabled.12"},
                    new MimeType{Type = ".xlsx",Mime = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
                    new MimeType{Type = ".xlt",Mime = "application/vnd.ms-excel"},
                    new MimeType{Type = ".xltm",Mime = "application/vnd.ms-excel.template.macroEnabled.12"},
                    new MimeType{Type = ".xltx",Mime = "application/vnd.openxmlformats-officedocument.spreadsheetml.template"},
                    new MimeType{Type = ".xlw",Mime = "application/vnd.ms-excel"},
                    new MimeType{Type = ".xml",Mime = "application/rss+xml"},
                    new MimeType{Type = ".xml",Mime = "application/xml"},
                    new MimeType{Type = ".xo",Mime = "application/vnd.olpc-sugar"},
                    new MimeType{Type = ".xof",Mime = "x-world/x-vrml"},
                    new MimeType{Type = ".xop",Mime = "application/xop+xml"},
                    new MimeType{Type = ".xpi",Mime = "application/x-xpinstall"},
                    new MimeType{Type = ".xpm",Mime = "image/x-xpixmap"},
                    new MimeType{Type = ".xpr",Mime = "application/vnd.is-xpr"},
                    new MimeType{Type = ".xps",Mime = "application/vnd.ms-xpsdocument"},
                    new MimeType{Type = ".xpw",Mime = "application/vnd.intercon.formnet"},
                    new MimeType{Type = ".xsd",Mime = "text/xml"},
                    new MimeType{Type = ".xsf",Mime = "text/xml"},
                    new MimeType{Type = ".xsl",Mime = "text/xml"},
                    new MimeType{Type = ".xslt",Mime = "application/xslt+xml"},
                    new MimeType{Type = ".xsm",Mime = "application/vnd.syncml+xml"},
                    new MimeType{Type = ".xsn",Mime = "application/octet-stream"},
                    new MimeType{Type = ".xspf",Mime = "application/xspf+xml"},
                    new MimeType{Type = ".xtp",Mime = "application/octet-stream"},
                    new MimeType{Type = ".xul",Mime = "application/vnd.mozilla.xul+xml"},
                    new MimeType{Type = ".xwd",Mime = "image/x-xwindowdump"},
                    new MimeType{Type = ".xyz",Mime = "chemical/x-xyz"},
                    new MimeType{Type = ".yaml",Mime = "text/yaml"},
                    new MimeType{Type = ".yang",Mime = "application/yang"},
                    new MimeType{Type = ".yin",Mime = "application/yin+xml"},
                    new MimeType{Type = ".z",Mime = "application/x-compress"},
                    new MimeType{Type = ".zaz",Mime = "application/vnd.zzazz.deck+xml"},
                    new MimeType{Type = ".zip",Mime = "application/x-zip-compressed"},
                    new MimeType{Type = ".zir",Mime = "application/vnd.zul"},
                    new MimeType{Type = ".zmm",Mime = "application/vnd.handheld-entertainment+xml"},

                }
            };
        }

        //private static void FillTypeList()
        //{
        //    if(_mimeTypesList != null)
        //        return;

        //    Assembly assembly = typeof(MimeTypeList).GetTypeInfo().Assembly;
        //    var names = assembly.GetManifestResourceNames();
        //    var stream = assembly.GetManifestResourceStream("MimeTypeExtension.otherTypes.json");
        //    if (stream == null)
        //        throw new FileNotFoundException("Could not load Resource");
        //    string jsonString = "";
        //    using(var reader = new StreamReader(stream))
        //    {
        //        jsonString = reader.ReadToEnd();
        //    }

        //    _mimeTypesList =
        //        Json.Deserialize<MimeTypeList>(
        //            jsonString); //Newtonsoft.Json.JsonConvert.DeserializeObject<MimeTypeList>(jsonString);

        //}
        /// <summary>
        /// You can Add or update your List of MIMES
        /// </summary>
        /// <param name="fileExtension">File extension eg. ".exe". The extension must start with  "."</param>
        /// <param name="mime">MIME Type string eg. "application/octet-stream". The string must contain "/"</param>
        /// <returns></returns>
        public static bool AddOrUpdateMimeType(string fileExtension, string mime)
        {
            if (string.IsNullOrEmpty(fileExtension))
                throw new ArgumentNullException(nameof(fileExtension),"fileExtension cannot be null");

            if (string.IsNullOrEmpty(mime))
                throw new ArgumentNullException(nameof(mime), "mime cannot be null");
            if (!fileExtension.StartsWith("."))
                throw new ArgumentException("fileExtension must start with a \".\"", nameof(fileExtension));

            if (!mime.Contains("/"))
                throw new ArgumentException("MIME must contain \"/\"", nameof(mime));

            if (_mimeTypesList.MimeTypes.Any(x => x.Type == fileExtension))
            {
                var mimeType = _mimeTypesList.MimeTypes.Find(x => x.Type == fileExtension);
                if (mimeType == null) return false;
                mimeType.Mime = mime;
                return true;

            }
            _mimeTypesList.MimeTypes.Add(new MimeType(){Type = fileExtension, Mime = mime});
            return true;
        }
        /// <summary>
        /// Get MimeType from URL
        /// </summary>
        /// <param name="uri"></param>
        /// <returns></returns>
        public static string MimeType(this Uri uri)
        {
            string path = uri.GetComponents(UriComponents.Path, UriFormat.Unescaped);
            FileInfo fi = new FileInfo(path);
            return fi.MimeType();
        }

        /// <summary>
        /// Get the MimeType from URL.
        /// If MimeType not found you can give a default MimeType
        /// </summary>
        /// <param name="uri"></param>
        /// <param name="defaultMime"></param>
        /// <returns></returns>
        public static string MimeTypeOrDefault(this Uri uri, string defaultMime = "application/octet-stream")
        {
            string path = uri.GetComponents(UriComponents.Path, UriFormat.Unescaped);
            FileInfo fi = new FileInfo(path);
            return fi.MimeTypeOrDefault(defaultMime);
        }

        /// <summary>
        /// Get the MimeType from File-Extension
        /// </summary>
        /// <param name="input">FileInfo</param>
        /// <returns>Returns the MIME-Type eg. Image/jpg</returns>
        public static string MimeType(this FileInfo input)
        {
           string extension = input.Extension;
           var mimeType = _mimeTypesList.MimeTypes.Find(x=> x.Type == extension);
            if(mimeType == null)
                return "";
            return mimeType.Mime;
        }
        /// <summary>
        /// Get the MimeType from File-Extension.
        /// If MimeType not found you can give a default MimeType
        /// </summary>
        /// <param name="input">FileInfo</param>
        /// <param name="defaultMime">Default MIME</param>
        /// <returns>Returns the MIME-Type eg. Image/jpg</returns>
        public static string MimeType(this FileInfo input, string defaultMime)
        {
            var mimeType = MimeType(input);
            if (string.IsNullOrEmpty(mimeType))
                mimeType = defaultMime;
            return mimeType;
        }
        /// <summary>
        /// Get the MimeType from File-Extension.
        /// If MIME not found you can give a default MIME
        /// If you don't give a default value the Default is:
        /// application/octet-stream
        /// </summary>
        /// <param name="input">FileInfo</param>
        /// <param name="defaultMime">Default MIME => default application/octet-stream</param>
        /// <returns>Returns the MIME-Type eg. Image/jpg or application/octet-stream</returns>
        public static string MimeTypeOrDefault(this FileInfo input, string defaultMime = "application/octet-stream")
        {
            return MimeType(input, defaultMime);
        }
    }
}

